// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDjtrzzZWsZ9KMtCu27ZC9
// Component: IzCzcwrfjf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_design_course.module.css"; // plasmic-import: tDjtrzzZWsZ9KMtCu27ZC9/projectcss
import sty from "./PlasmicNavbar.module.css"; // plasmic-import: IzCzcwrfjf/css

createPlasmicElementProxy;

export type PlasmicNavbar__VariantMembers = {};
export type PlasmicNavbar__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbar__VariantsArgs;
export const PlasmicNavbar__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbar__ArgsType = {};
type ArgPropType = keyof PlasmicNavbar__ArgsType;
export const PlasmicNavbar__ArgProps = new Array<ArgPropType>();

export type PlasmicNavbar__OverridesType = {
  frame1?: p.Flex<"div">;
};

export interface DefaultNavbarProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbar__RenderFunc(props: {
  variants: PlasmicNavbar__VariantsArgs;
  args: PlasmicNavbar__ArgsType;
  overrides: PlasmicNavbar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"frame1"}
      data-plasmic-override={overrides.frame1}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.frame1
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___75Vv5
        )}
        onClick={async event => {
          const $steps = {};
          $steps["goToHome"] = true
            ? (() => {
                const actionArgs = {
                  destination: __wrapUserFunction(
                    {
                      type: "InteractionArgLoc",
                      actionName: "navigation",
                      interactionUuid: "b8VbcWVIT",
                      componentUuid: "IzCzcwrfjf",
                      argName: "destination"
                    },
                    () => `/home`
                  )
                };
                return __wrapUserFunction(
                  {
                    type: "InteractionLoc",
                    actionName: "navigation",
                    interactionUuid: "b8VbcWVIT",
                    componentUuid: "IzCzcwrfjf"
                  },
                  () =>
                    (({ destination }) => {
                      __nextRouter?.push(destination);
                    })?.apply(null, [actionArgs]),
                  actionArgs
                );
              })()
            : undefined;
          if (
            typeof $steps["goToHome"] === "object" &&
            typeof $steps["goToHome"].then === "function"
          ) {
            $steps["goToHome"] = await __wrapUserPromise(
              {
                type: "InteractionLoc",
                actionName: "navigation",
                interactionUuid: "b8VbcWVIT",
                componentUuid: "IzCzcwrfjf"
              },
              $steps["goToHome"]
            );
          }
        }}
      >
        {"Home"}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__amIo
        )}
        onClick={async event => {
          const $steps = {};
          $steps["goToOurWork"] = true
            ? (() => {
                const actionArgs = {
                  destination: __wrapUserFunction(
                    {
                      type: "InteractionArgLoc",
                      actionName: "navigation",
                      interactionUuid: "alPCTOCEw",
                      componentUuid: "IzCzcwrfjf",
                      argName: "destination"
                    },
                    () => `/our-work`
                  )
                };
                return __wrapUserFunction(
                  {
                    type: "InteractionLoc",
                    actionName: "navigation",
                    interactionUuid: "alPCTOCEw",
                    componentUuid: "IzCzcwrfjf"
                  },
                  () =>
                    (({ destination }) => {
                      __nextRouter?.push(destination);
                    })?.apply(null, [actionArgs]),
                  actionArgs
                );
              })()
            : undefined;
          if (
            typeof $steps["goToOurWork"] === "object" &&
            typeof $steps["goToOurWork"].then === "function"
          ) {
            $steps["goToOurWork"] = await __wrapUserPromise(
              {
                type: "InteractionLoc",
                actionName: "navigation",
                interactionUuid: "alPCTOCEw",
                componentUuid: "IzCzcwrfjf"
              },
              $steps["goToOurWork"]
            );
          }
        }}
      >
        {"Our Work"}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___02Sx6
        )}
        onClick={async event => {
          const $steps = {};
          $steps["goToServices"] = true
            ? (() => {
                const actionArgs = {
                  destination: __wrapUserFunction(
                    {
                      type: "InteractionArgLoc",
                      actionName: "navigation",
                      interactionUuid: "h6PgMd-2c",
                      componentUuid: "IzCzcwrfjf",
                      argName: "destination"
                    },
                    () => `/services`
                  )
                };
                return __wrapUserFunction(
                  {
                    type: "InteractionLoc",
                    actionName: "navigation",
                    interactionUuid: "h6PgMd-2c",
                    componentUuid: "IzCzcwrfjf"
                  },
                  () =>
                    (({ destination }) => {
                      __nextRouter?.push(destination);
                    })?.apply(null, [actionArgs]),
                  actionArgs
                );
              })()
            : undefined;
          if (
            typeof $steps["goToServices"] === "object" &&
            typeof $steps["goToServices"].then === "function"
          ) {
            $steps["goToServices"] = await __wrapUserPromise(
              {
                type: "InteractionLoc",
                actionName: "navigation",
                interactionUuid: "h6PgMd-2c",
                componentUuid: "IzCzcwrfjf"
              },
              $steps["goToServices"]
            );
          }
        }}
      >
        {"Services"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame1: ["frame1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  frame1: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbar__VariantsArgs;
    args?: PlasmicNavbar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavbar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavbar__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNavbar__ArgProps,
          internalVariantPropNames: PlasmicNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame1") {
    func.displayName = "PlasmicNavbar";
  } else {
    func.displayName = `PlasmicNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbar = Object.assign(
  // Top-level PlasmicNavbar renders the root element
  makeNodeComponent("frame1"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavbar
    internalVariantProps: PlasmicNavbar__VariantProps,
    internalArgProps: PlasmicNavbar__ArgProps
  }
);

export default PlasmicNavbar;
/* prettier-ignore-end */
